#! /bin/sh


# shorten commands
_bc() {
	bspc config "$@"
}

_is_command() {
	command -v "$1" > /dev/null
}

_if_exists_exec() {
	cmd="$1"
	launch_script="$2"	
	
	if _is_command ${cmd}; then
		if [ -f ${launch_script} ]; then
			${launch_script} &
		fi
	fi
}

if [[ $(xrandr -q | grep 'DP-5 connected') ]]; then
	xrandr --output HDMI-0 --primary --mode 1920x1080 --rate 144 --rotate normal --output DP-5 --mode 1360x768 --rotate normal --left-of HDMI-0
fi

bspc monitor HDMI-0 -d I II III IV V 
# Enforce HDMI-0 to have I
bspc monitor ^1 -s HDMI-0
bspc monitor DP-5 -d VI VII VIII IX X

# Window Management
_bc border_width	3
_bc window_gap          5
_bc split_ratio        	0.5
_bc borderless_monocle  true
_bc gapless_monocle     false

# autostart applications

pgrep -x sxhkd > /dev/null || (_is_command sxhkd && sxhkd &)

_is_command picom && picom --config $HOME/.config/picom/picom.conf &

_is_command dunst && dunst &

_if_exists_exec feh $HOME/.fehbg

_if_exists_exec polybar $HOME/.config/polybar/launch.sh

